
name: 'stock_market_dbt_analytics'             
version: '1.0'
config-version: 2                  

profile: 'profiles'           

target-path: "target"               # where dbt will write compiled SQL
clean-targets:                      # folders to clean when you run `dbt clean`
  - "target"
  - "dbt_modules"

model-paths: ["models"]            
analysis-paths: ["analyses"]        # optional: for ad-hoc analysis SQL files
test-paths: ["tests"]               # optional: for custom tests
macro-paths: ["macros"]             # optional: for macros

models:
  stock_market_dbt_analytics:

    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table
